host = "localhost"  # My sql host
user = "root"  # My sql username
password = "jeet7223"  # Mysql Password
database = "goo_net"  # Database Name
charset = "utf8mb4"  # do not change it if it works with it
auth_plugin = 'mysql_native_password'  # do not change it if it works with it
BUCKET_ACCESS_KEY_ID = 'AKIARYF3TESSVORZQ3ZY'
BUCKET_ACCESS_SECRET_KEY = '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'
BUCKET_NAME = 'car-catalogues'
root_path = "/var/www/html/scraper/goo-net/"